### ISSUE TITLE
Connection lost 

### ISSUE THREAD

**Issue by ursusHU** [benzman81/homebridge-bravia-simple#1]
If the tv is off for a longer period, the status in HomeKit changes to ‘not answering’ and the problem can be solved only with turning on the tv with the remote. Then it works perfectly again.

**Comment by benzman81** [comment]
@ursusHU what do you mean by „longer period“? Do you have a reproducible time frame I can check?

**Comment by ursusHU** [comment]
It is occuring around 17-18 minutes after turning off the tv. I’m using hoobs for Homebridge (if this matters).

**Comment by benzman81** [comment]
By turning off you mean putting it in standby or cutting power off via pulling the cable for example.

**Comment by ursusHU** [comment]
Standby mode, turning off with your plugin for example.

**Comment by ursusHU** [comment]
This is what I found in the logs, it is permanently there:
[Homebridge] [3/16/2020, 12:58:05 AM] [BraviaSimpleHomebridgePlatform] getActiveIdentifier to:2[Homebridge] [3/16/2020, 12:58:05 AM] [BraviaSimpleHomebridgePlatform] Background update:true 2[Homebridge] [3/16/2020, 12:58:05 AM] [BraviaPlatform] Exception!  SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSucces (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:314:26)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:676:9)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by ursusHU** [comment]
When I turn off the TV (standby) this message arrives time to time:
[Homebridge] [3/16/2020, 1:55:36 AM] [BraviaSimpleHomebridgePlatform] Background update with error:false 0 Error: Bravia 'Sony Bravia' is not powered on.
    at BraviaHomebridgeTV.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-bravia-simple/index.js:237:16)
    at /home/hoobs/.hoobs/node_modules/homebridge-bravia-simple/index.js:173:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
	
And this message arrives when the TV gets out of sync:

[Homebridge] [3/16/2020, 2:12:37 AM] [BraviaSimpleHomebridgePlatform] Background update with error:false 0 Bravia 'Sony Bravia' is not reachable.

**Comment by benzman81** [comment]
Ok, thats good information. Will check it next weekend.

**Comment by benzman81** [comment]
@ursusHU so I had a look at it.

The message  **Background update with error:false 0 Error: Bravia 'Sony Bravia' is not powered on.** is normal and should occur whenever the tv is in standby and reachable and the plugin requests the current state of the tv every poll interval. With my Bravia the home app shows that it is turned off and I can push it to turn it on, even after 10 hours of standby.

The message **Background update with error:false 0 Bravia 'Sony Bravia' is not reachable.** is also normal and should occur whenever the tv if is not reachable and the plugin requests the current state of the tv every poll interval. With my Bravia the home app shows that it is unavailable and I can't turn it on since it is not reachable. My Bravia only reaches this state if I pull the power plug, which I do daily by home home automation.

The message **Background update:true 2** is also normal and should occur whenever the tv is powered on and reachable and the plugin requests the current state of the tv every poll interval. It shows the current power state and the active identifier (channel).

The message **[BraviaPlatform] Exception! SyntaxError: Unexpected token < in JSON at position 0** is not from my plugin ;-).
 
So for you initial request:

> If the tv is off for a longer period, the status in HomeKit changes to ‘not answering’ and the problem can be solved only with turning on the tv with the remote. Then it works perfectly again.

This seems to be a model specific problem as I cannot reproduce it. Maybe you can analyze it an provide a pull request for it.

**Comment by ursusHU** [comment]
My TV is a Bravia KDL-50W815B. I have checked other plugins for the TV, none of them has issue with losing the connection. (they have others :) ) What I see that every other plugin requires MAC address, and it is stated that it is necessary for WOL feature, maybe that's the point. Could it be?

**Comment by benzman81** [comment]
@ursusHU can you check this setting:

Enable remote start on your TV: [Settings] → [Network] → [Home Network Setup] → [Remote Start] → [On]

Is it set to [On]? if not, turn it on and test again.

**Comment by benzman81** [comment]
Here is an overview of the possible power states and its possibilities: https://pro-bravia.sony.net/faq/62/

"setPowerStatus" is the API function the plugin uses.

**Comment by ursusHU** [comment]
Yes both Remote start and also in IP Control the Simple IP control function is on.
