### ISSUE TITLE
Error plugin log. Plugin not work

### ISSUE THREAD

**Issue by znammut** [benzman81/homebridge-bravia-simple#2]
Error log:Background update with error:false 0 Error: Failed to parse the error response: [object Object].
    at /usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/bravia/src/bravia.js:191:24
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/xml2js/lib/parser.js:308:18)
    at Parser.emit (events.js:315:20)
    at SAXParser.onerror (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/xml2js/lib/parser.js:123:26)
    at emit (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/sax/lib/sax.js:624:35)
    at error (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/bravia/src/bravia.js:183:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia-simple/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Node.js v12.18.0
Npm v6.14.4

**Comment by benzman81** [comment]
When does the error occur and what is your configuration?

**Comment by znammut** [comment]
Hi

The error occurs after saving the configuration and restarting homebridge, while the TV is turned on. If you turn off the TV, then the error becomes like this:

    background update with error:false 0 Error: Bravia 'Sony TV' is not powered on.
    at BraviaHomebridgeTV.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia-simple/index.js:266:16)
    at /usr/local/lib/node_modules/homebridge-bravia-simple/index.js:181:5

Model my TV: bravia kdl-42w635a 

There is no Enter Pre-Shared Key in my TV menu, but everyone can be allowed to walk without a key

my config

      {
            "platform": "BraviaSimpleHomebridgePlatform",
            "tvs": [
                {
                    "name": "Sony TV",
                    "ip": "192.168.17.44",
                    "port": 80,
                    "psk": "0000",
                    "pollinterval": 15000,
                    "add_lightbuildspeaker": false,
                    "inputs": [
                        {
                            "name": "HDMI1",
                            "source": "extInput:hdmi",
                            "num": 1
                        },
                        {
                            "name": "HDMI2",
                            "source": "extInput:hdmi",
                            "num": 2
                        },
                        {
                            "name": «1 canal",
                            "source": "tv:dvbc",
                            "num": 411
                        },
                        {
                            "name": «2 canal",
                            "source": "tv:dvbc",
                            "num": 412
                        }
                    ]
                }
            ]
        },


Sorry for my English

Dmitry

> 27 окт. 2020 г., в 21:20, Markus Krüger <notifications@github.com> написал(а):
> 
> When does the error occur and what is your configuration?
